{% set name = "git-remote-codecommit" %}
{% set version = "1.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd4a9ba3fbd88cd455a8e2087765e415da0beaae9932d4e84010069a536de24e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - git-remote-codecommit = git_remote_codecommit:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - botocore >=1.17.0

test:
  imports:
    - git_remote_codecommit
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/aws/git-remote-codecommit
  summary: A Git extension for pushing and pulling from AWS CodeCommit.
  description: |
    This package enables pushing and pulling from repository URLs prefixed with codecommit://
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/aws/git-remote-codecommit
  dev_url: https://github.com/aws/git-remote-codecommit

extra:
  recipe-maintainers:
    - SylvainCorlay
